FileVersion = 1

[Project]
Name = "Beef.Math"
DefaultNamespace = "BeefMath"

[Configs.Debug.Win64]
BuildKind = "StaticLib"

[Configs.Release.Win64]
BuildKind = "StaticLib"

[Configs.Paranoid.Win64]
BuildKind = "StaticLib"
